# Generated by Django 4.2.11 on 2026-04-06 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodShortageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('alert_level', models.CharField(choices=[('low', 'Low Stock'), ('critical', 'Critical Shortage'), ('emergency', 'Emergency Shortage')], max_length=20)),
                ('available_donors', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('shortage_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
