# Generated by Django 6.0.4 on 2026-04-12 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0002_bloodshortagealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='alert_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times SMS alerts have been sent for this request'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='units_fulfilled',
            field=models.PositiveIntegerField(default=0, help_text='How many units have been received so far'),
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('minimum_threshold', models.PositiveIntegerField(default=3, help_text='Send auto-alert when stock falls below this level')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Stock',
                'verbose_name_plural': 'Blood Stock',
                'ordering': ['blood_type'],
            },
        ),
    ]
