# Generated by Django 6.0.4 on 2026-04-12 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0003_emergencyrequest_alert_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=20)),
                ('requester_relationship', models.CharField(help_text='e.g. Patient, Mother, Brother', max_length=100)),
                ('patient_name', models.CharField(max_length=150)),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_needed', models.PositiveIntegerField(default=1)),
                ('urgency_level', models.CharField(choices=[('critical', 'Critical - Life Threatening'), ('urgent', 'Urgent - Within 2 Hours'), ('normal', 'Normal - Within 24 Hours')], default='urgent', max_length=20)),
                ('hospital_ward', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Alerts Sent'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('linked_emergency_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_requests', to='staff_portal.emergencyrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_public_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Blood Request',
                'verbose_name_plural': 'Public Blood Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
