# Generated by Django 6.0.4 on 2026-04-13 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0004_publicbloodrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('donor_added', 'Donor Added'), ('donor_edited', 'Donor Edited'), ('donor_deleted', 'Donor Deleted'), ('donor_toggled', 'Donor Availability Toggled'), ('request_created', 'Emergency Request Created'), ('request_closed', 'Request Closed'), ('request_fulfilled', 'Request Fulfilled'), ('request_resent', 'Alerts Re-Sent'), ('stock_updated', 'Blood Stock Updated'), ('public_approved', 'Public Request Approved'), ('public_rejected', 'Public Request Rejected'), ('staff_registered', 'Staff Registered'), ('login', 'Staff Login'), ('logout', 'Staff Logout')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_donor_id', models.IntegerField(blank=True, null=True)),
                ('related_request_id', models.IntegerField(blank=True, null=True)),
                ('staff_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
