# Generated by Django 6.0.4 on 2026-04-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0005_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('donor_added', 'Donor Added'), ('donor_edited', 'Donor Edited'), ('donor_deleted', 'Donor Deleted'), ('donor_toggled', 'Donor Availability Toggled'), ('request_created', 'Emergency Request Created'), ('request_closed', 'Request Closed'), ('request_fulfilled', 'Request Fulfilled'), ('request_escalated', 'Request Escalated'), ('request_resent', 'Alerts Re-Sent'), ('stock_updated', 'Blood Stock Updated'), ('public_approved', 'Public Request Approved'), ('public_rejected', 'Public Request Rejected'), ('staff_registered', 'Staff Registered'), ('login', 'Staff Login'), ('logout', 'Staff Logout')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='urgency_level',
            field=models.CharField(choices=[('critical', 'Critical — Immediate Response Required'), ('moderate', 'Moderate — Within 2 Hours'), ('normal', 'Normal — Within 24 Hours')], default='urgent', max_length=20),
        ),
    ]
