# Generated by Django 6.0.4 on 2026-04-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0006_alter_activitylog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodstock',
            options={'ordering': ['blood_type'], 'verbose_name': 'Blood Stock', 'verbose_name_plural': 'Blood Stocks'},
        ),
        migrations.RenameField(
            model_name='bloodstock',
            old_name='units_available',
            new_name='current_units',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='minimum_threshold',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='critical_level',
            field=models.PositiveIntegerField(default=5, help_text='Critical stock level - immediate alert'),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='minimum_level',
            field=models.PositiveIntegerField(default=10, help_text='Minimum acceptable stock level'),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='optimal_level',
            field=models.PositiveIntegerField(default=50, help_text='Optimal stock level for this blood type'),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical', 'Critical Shortage Alert'), ('low', 'Low Stock Alert'), ('restock', 'Restock Notification')], max_length=20)),
                ('current_units', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('blood_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='staff_portal.bloodstock')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-sent_at'],
            },
        ),
    ]
