# Generated by Django 4.2.11 on 2026-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('location', models.CharField(choices=[('Nsambya', 'Nsambya'), ('Kabalagala', 'Kabalagala'), ('Namuwongo', 'Namuwongo'), ('Makindye', 'Makindye'), ('Kibuli', 'Kibuli'), ('Kampala Central', 'Kampala Central'), ('Ntinda', 'Ntinda'), ('Bukoto', 'Bukoto'), ('Other', 'Other')], default='Other', max_length=100)),
                ('physical_address', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('profile_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-date_registered'],
            },
        ),
    ]
