# Generated by Django 6.0.4 on 2026-04-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
    ]
