# Generated by Django 6.0.4 on 2026-04-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-date_registered'], 'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
    ]
