# Generated by Django 4.2.11 on 2026-04-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
