# Generated by Django 4.2.11 on 2026-04-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('phone', 'Phone')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='google_profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
