# Generated by Django 6.0.4 on 2026-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donor_auth_method_donor_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_count_12_months',
            field=models.PositiveIntegerField(default=0, help_text='Donations in last 12 months'),
        ),
        migrations.AddField(
            model_name='donor',
            name='next_eligible_date',
            field=models.DateField(blank=True, help_text='Date when donor can donate again', null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of donations made'),
        ),
    ]
