# Generated by Django 4.2.11 on 2026-04-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('donor_response', models.CharField(choices=[('no_response', 'No Response'), ('confirmed', 'Confirmed — Will Donate'), ('declined', 'Declined')], default='no_response', max_length=20)),
                ('at_message_id', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='donors.donor')),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
