# Generated by Django 4.2.11 on 2026-04-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('staff_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='emergency_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='staff_portal.emergencyrequest'),
        ),
    ]
