# Generated by Django 4.2.11 on 2026-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_smsnotification_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='message_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
