# Generated by Django 4.2.11 on 2026-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_message_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
